# Application configuration
application:
  # Name of the application. This is the identifier that other services will use to register and discover this service in the Eureka server.
  name: giftCard-api-gateway

# Server configuration
server:
  # Port on which the application will run. Port 4040 is the standard port for Eureka servers.
  port: 4040

# Eureka configuration
eureka:
  client:
    # Indicates whether this service should register with the Eureka server. In this case, it is disabled.
    register-with-eureka: false
    service-url:
      # URL of the Eureka server. This service will connect to Eureka at this URL to discover other services.
      defaultZone: http://localhost:8761/eureka/

spring:
  config:
    import:
      - classpath:routes/eureka.yml