# Gateway configuration
spring:
  cloud:
    gateway:
      routes:
        # Route configuration to access the Eureka UI through the Gateway.
        - id: eureka-ui
          # URI of the Eureka server. Requests will be redirected to this URL.
          uri: http://localhost:8761
          # Predicate that defines when this route will be activated. In this case, it will be activated for any path starting with `/eureka/`.
          predicates:
            - Path=/eureka-ui/**
          # Filter that rewrites the request path to remove the `/eureka` prefix before redirecting it to the Eureka server.
          filters:
            - RewritePath=/eureka-ui/(?<segment>.*), /$\{segment}
        # Route configuration to access the Eureka UI through the Gateway.
        - id: eureka-static
          # URI of the Eureka server. Requests will be redirected to this URL.
          uri: http://localhost:8761
          # Predicate that defines when this route will be activated. In this case, it will be activated for any path starting with `/eureka/`.
          predicates:
            - Path=/eureka/**