# Application configuration
spring:
  application:
    name: giftCard-auth-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/giftCard-auth-service
    username: admin
    password: adminpassword
# Server configuration
server:
  port: 5000
  error:
    include-stacktrace: never

# Eureka configuration
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


