# Application configuration
spring:
  application:
    name: giftCard-auth-service
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/giftCard-manager}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:adminpassword}
# Server configuration
server:
  port: 0
  error:
    include-stacktrace: never

# Eureka configuration
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}


