version: '3.8'



services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpassword
    ports:
      - "5672:5672"
      - "15672:15672"

  giftCard-auth-service:
    image: postgres:latest
    container_name: giftCard-manager
    environment:
      POSTGRES_DB: giftCard-manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5433:5432"
    restart: always