# Application configuration
spring:
  application:
    name: giftCard-manager
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5433/giftCard-manager}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:adminpassword}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:adminpassword}
# Server configuration
server:
  port: 0
#  error:
#    include-stacktrace: never

# Eureka configuration
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}


